title: Shanbag.us
description: Simple site
# theme: minima
remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

description: "Welcome to my website powered by Hydejack."
author:
  name: "Your Name"
  email: "you@example.com"
  github: username
  linkedin: your-linkedin
  twitter: your-handle

menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
